kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm install

- name: unit test
  image: node
  commands:
  - npm test

- name: hello main
  image: alpine
  commands:
  - echo "Hello main"
  when:
    branch:
    - main

- name: hello dev
  image: alpine
  commands:
  - echo "Hello dev"
  when:
    branch:
    - dev
    event:
    - pull_request

trigger:
  event:
  - push