kind: pipeline
type: docker
name: default

steps:
  - name: install pkg
    image: node:alpine
    commands:
    - npm i
  
  - name: unit tests
    image: node:alpine
    commands:
    - npm test

  - name: secrets
    image: alpine
    environment:
      SECRET_TEXT:
        from_secret: SECRET_TEXT
    commands:
    - echo $SECRET_TEXT > .env
    - cat .env
