kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install

  - name: test
    image: node:alpine
    commands:
      - npm test

trigger:
  event:
  - push
